#!/bin/bash
set -eou pipefail

./stop

./0_check_dependencies.sh
./1_create_openshift_project.sh
./2_build_and_push_containers.sh
./3_start_conjur_cluster.sh
./4_configure_master.sh
./5_create_load_balancer.sh
./6_configure_standbys.sh
./7_configure_followers.sh
./8_print_config.sh
