#!/bin/bash -e

./stop

./0_create_openshift_project.sh
./1_build_and_push_containers.sh
./2_start_conjur_cluster.sh
./3_configure_master.sh
./4_create_load_balancer.sh
./5_configure_standbys.sh
./6_configure_followers.sh
./7_print_config.sh
