#!/bin/bash
set -eou pipefail

. utils.sh

oc project default

if has_project $CONJUR_PROJECT_NAME; then
  oc delete project $CONJUR_PROJECT_NAME

  printf "Waiting for $CONJUR_PROJECT_NAME project deletion to complete"

  while : ; do
    printf "..."
    
    if has_project "$CONJUR_PROJECT_NAME"; then
      sleep 5
    else
      break
    fi
  done

  echo ""
fi

echo "Conjur environment purged."
