#!/bin/bash
set -eou pipefail

./stop

./0_create_openshift_project.sh
./1_initialize_conjur.sh
./2_build_and_push_container.sh
./3_load_conjur_policies.sh
./4_store_conjur_cert.sh
./5_store_conjur_api_key.sh
./6_deploy_app.sh
